Repository realm/realm-dotnet, pull requests merged in 2018-04, with the labels that each got.

#1713 Rename Permission to PathPermission
  CHANGELOG.md
  Platform.PCL/Realm.Sync.PCL/Realm.Sync.PCL.csproj
  Platform.PCL/Realm.Sync.PCL/UserPCL.cs
  Realm/Realm.Sync/Permissions/PathPermission.cs
  Realm/Realm.Sync/Realm.Sync.csproj
  Realm/Realm.Sync/User.cs
  Tests/Tests.Sync.Shared/PermissionsTests.cs
Labels: Breaking

#1718 Add missing GCHandle guard for callback method
  Realm/Realm.Sync/Subscription.cs
  Tests/Tests.Sync.Shared/PartialSyncTests.cs
Labels: T:Bug

#1714 Expose classes for object level permissions
  CHANGELOG.md
  Platform.PCL/Realm.PCL/RealmObjectPCL.cs
  Platform.PCL/Realm.Sync.PCL/Extensions/RealmSyncExtensionsPCL.cs
  Platform.PCL/Realm.Sync.PCL/ObjectLevelPermissions/PermissionExtensionsPCL.cs
  Platform.PCL/Realm.Sync.PCL/Realm.Sync.PCL.csproj
  Realm/Realm.Sync/Credentials.cs
  Realm/Realm.Sync/Extensions/RealmSyncExtensions.cs
  Realm/Realm.Sync/Handles/SharedRealmHandleExtensions.cs
  Realm/Realm.Sync/ObjectLevelPermissions/ClassPermission.cs
  Realm/Realm.Sync/ObjectLevelPermissions/ClassPrivileges.cs
  Realm/Realm.Sync/ObjectLevelPermissions/ObjectPrivileges.cs
  Realm/Realm.Sync/ObjectLevelPermissions/Permission.cs
  Realm/Realm.Sync/ObjectLevelPermissions/PermissionExtensions.cs
  Realm/Realm.Sync/ObjectLevelPermissions/PermissionRole.cs
  Realm/Realm.Sync/ObjectLevelPermissions/PermissionUser.cs
  Realm/Realm.Sync/ObjectLevelPermissions/RealmPermission.cs
  Realm/Realm.Sync/ObjectLevelPermissions/RealmPrivileges.cs
  Realm/Realm.Sync/Permissions/PermissionChange.cs
  Realm/Realm.Sync/Permissions/PermissionOffer.cs
  Realm/Realm.Sync/Permissions/PermissionOfferResponse.cs
  Realm/Realm.Sync/Realm.Sync.csproj
  Realm/Realm.Sync/Subscription.cs
  Realm/Realm.Sync/SyncConfiguration.cs
  Realm/Realm/Migration.cs
  Realm/Realm/Native/NativeCommon.cs
  Realm/Realm/RealmList.cs
  Realm/Realm/RealmObject.cs
  Realm/Realm/Schema/RealmSchema.cs
  Tests/Tests.Sync.Shared/ObjectLevelPermissionsTests.cs
  Tests/Tests.Sync.Shared/SyncTestBase.cs
  Tests/Tests.Sync.Shared/SyncTestHelpers.cs
  Tests/Tests.Sync.Shared/Tests.Sync.Shared.projitems
  wrappers/src/shared_realm_cs.cpp
  wrappers/src/sync_manager_cs.cpp
Labels: G:Rangers, T:Feature

#1722 Fix Subscription.UnsubscribeAsync failing sporadically.
  Realm/Realm.Sync/ObjectLevelPermissions/ResultSets.cs
  Realm/Realm.Sync/Realm.Sync.csproj
  Realm/Realm.Sync/Subscription.cs
  Tests/Tests.Sync.Shared/ObjectLevelPermissionsTests.cs
Labels: G:Rangers

#1721 Add password reset wrappers
  CHANGELOG.md
  Platform.PCL/Realm.Sync.PCL/UserPCL.cs
  Realm/Realm.Sync/Helpers/AuthenticationHelper.cs
  Realm/Realm.Sync/User.cs
Labels: G:Rangers
