Repository realm/realm-dotnet, pull requests merged in 2018-06, with the labels that each got.

#1750 Partial -> query-based sync
  CHANGELOG.md
  Jenkinsfile
  Platform.PCL/Realm.Sync.PCL/Configurations/FullSyncConfigurationPCL.cs
  Platform.PCL/Realm.Sync.PCL/Configurations/QueryBasedSyncConfigurationPCL.cs
  Platform.PCL/Realm.Sync.PCL/Configurations/SyncConfigurationBasePCL.cs
  Platform.PCL/Realm.Sync.PCL/Configurations/SyncConfigurationPCL.cs
  Platform.PCL/Realm.Sync.PCL/Extensions/RealmSyncExtensionsPCL.cs
  Platform.PCL/Realm.Sync.PCL/Realm.Sync.PCL.csproj
  Platform.PCL/Realm.Sync.PCL/SubscriptionPCL.cs
  Platform.PCL/Realm.Sync.PCL/SyncConfigurationPCL.cs
  Realm/Realm.Sync/Configurations/FullSyncConfiguration.cs
  Realm/Realm.Sync/Configurations/QueryBasedSyncConfiguration.cs
  Realm/Realm.Sync/Configurations/SyncConfiguration.cs
  Realm/Realm.Sync/Configurations/SyncConfigurationBase.cs
  Realm/Realm.Sync/Extensions/RealmSyncExtensions.cs
  Realm/Realm.Sync/ObjectLevelPermissions/ClassPermission.cs
  Realm/Realm.Sync/ObjectLevelPermissions/RealmPermission.cs
  Realm/Realm.Sync/Permissions/PermissionOfferResponse.cs
  Realm/Realm.Sync/Realm.Sync.csproj
  Realm/Realm.Sync/Session.cs
  Realm/Realm.Sync/Subscription.cs
  Realm/Realm.Sync/User.cs
  Tests/Tests.Sync.Shared/MergeByPKTests.cs
  Tests/Tests.Sync.Shared/ObjectLevelPermissionsTests.cs
  Tests/Tests.Sync.Shared/PermissionsTests.cs
  Tests/Tests.Sync.Shared/QueryBasedSyncTests.cs
  Tests/Tests.Sync.Shared/SSLConfigurationTests.cs
  Tests/Tests.Sync.Shared/SessionTests.cs
  Tests/Tests.Sync.Shared/SyncConfigurationTests.cs
  Tests/Tests.Sync.Shared/SyncTestHelpers.cs
  Tests/Tests.Sync.Shared/SynchronizedInstanceTests.cs
  Tests/Tests.Sync.Shared/Tests.Sync.Shared.projitems
  Tests/Tests.iOS/AppDelegate.cs
Labels: G:Rangers, P:2 Expected, T:Feature

#1744 Upgrade to new Fody
  CHANGELOG.md
  Manual Tests/NuGetReleaseTests/Tests.Android/Tests.Android.csproj
  Manual Tests/NuGetReleaseTests/Tests.Android/packages.config
  Manual Tests/NuGetReleaseTests/Tests.Win32/Tests.Win32.csproj
  Manual Tests/NuGetReleaseTests/Tests.Win32/packages.config
  Manual Tests/NuGetReleaseTests/Tests.XamarinMac/Tests.XamarinMac.csproj
  Manual Tests/NuGetReleaseTests/Tests.XamarinMac/packages.config
  Manual Tests/NuGetReleaseTests/Tests.iOS/Tests.iOS.csproj
  Manual Tests/NuGetReleaseTests/Tests.iOS/packages.config
  Manual Tests/ThreeLayerRealmXFNuGet/PurePCLViewModel/PurePCLViewModel.csproj
  Manual Tests/ThreeLayerRealmXFNuGet/PurePCLViewModel/packages.config
  Manual Tests/ThreeLayerRealmXFNuGet/ThreeLayerRealmXFNuGet/ThreeLayerRealmXFNuGet.Droid/ThreeLayerRealmXFNuGet.Droid.csproj
  Manual Tests/ThreeLayerRealmXFNuGet/ThreeLayerRealmXFNuGet/ThreeLayerRealmXFNuGet.Droid/packages.config
  Manual Tests/ThreeLayerRealmXFNuGet/ThreeLayerRealmXFNuGet/ThreeLayerRealmXFNuGet.iOS/ThreeLayerRealmXFNuGet.iOS.csproj
  Manual Tests/ThreeLayerRealmXFNuGet/ThreeLayerRealmXFNuGet/ThreeLayerRealmXFNuGet.iOS/packages.config
  NuGet/Realm.Database/Realm.Database.nuspec
  Realm/Realm.Sync/Realm.Sync.csproj
  Tests/Tests.Android/Tests.Android.csproj
  Tests/Tests.Android/packages.config
  Tests/Tests.NetCore/Tests.NetCore.csproj
  Tests/Tests.UWP/Tests.UWP.csproj
  Tests/Tests.Win32/Tests.Win32.csproj
  Tests/Tests.Win32/packages.config
  Tests/Tests.XamarinMac/Tests.XamarinMac.csproj
  Tests/Tests.XamarinMac/packages.config
  Tests/Tests.iOS/Tests.iOS.csproj
  Tests/Tests.iOS/packages.config
  Weaver/RealmWeaver.Fody/Analytics.cs
  Weaver/RealmWeaver.Fody/ImportedReferences.cs
  Weaver/RealmWeaver.Fody/ModuleWeaver.cs
  Weaver/RealmWeaver.Fody/RealmWeaver.Fody.csproj
  Weaver/WeaverTests/RealmFreeAssemblyToProcess/RealmFreeAssemblyToProcess.csproj
  Weaver/WeaverTests/RealmWeaver.Tests/FodyWeavers.xml
  Weaver/WeaverTests/RealmWeaver.Tests/RealmWeaver.Tests.csproj
  Weaver/WeaverTests/RealmWeaver.Tests/WeaveEmptyTests.cs
  Weaver/WeaverTests/RealmWeaver.Tests/WeaverTestBase.cs
  Weaver/WeaverTests/RealmWeaver.Tests/WeaverTests.cs
  Weaver/WeaverTests/RealmWeaver.Tests/app.config
  Weaver/WeaverTests/RealmWeaver.Tests/packages.config
Labels: T:Enhancement

#1729 Make WriteAsync wait for changes asynchronously
  CHANGELOG.md
  Platform.PCL/Realm.PCL/RealmPCL.cs
  Realm/Realm/Handles/SharedRealmHandle.cs
  Realm/Realm/Realm.cs
  Tests/Tests.Shared/AsyncTests.cs
  wrappers/src/shared_realm_cs.cpp
Labels: T:Enhancement

#1753 Don't throw an exception when adding an object to a different instanc…
  CHANGELOG.md
  Realm/Realm/Realm.cs
  Tests/Tests.Shared/ObjectIntegrationTests.cs
Labels: G:Rangers, O:User PE/EE, P:2 Expected, T:Bug

#1752 Expose NewModifiedIndices
  CHANGELOG.md
  Realm/Realm/Handles/NotifiableObjectHandleBase.cs
  Realm/Realm/Linq/IRealmCollection.cs
  Realm/Realm/RealmCollectionBase.cs
  Tests/Tests.Shared/NotificationTests.cs
  wrappers/src/notifications_cs.hpp
Labels: G:Rangers, O:User PE/EE, P:1 Required, T:Enhancement
