Repository realm/realm-dotnet, pull requests merged in 2019-11, with the labels that each got.

#1923 ROS-110: Expose userId and isAdmin as parameters to Credentials.CustomRefreshToken
  CHANGELOG.md
  Realm/Realm/Sync/Credentials.cs
  Tests/Realm.Tests/Sync/CredentialsTests.cs
Labels: T-Enhancement

#1924 Allow [Required] on IList<string>
  CHANGELOG.md
  Realm/Realm.Fody/Extensions/PropertyDefinitionExtensions.cs
  Realm/Realm.Fody/ModuleWeaver.cs
  Tests/Realm.Tests/Database/ListOfPrimitivesTests.cs
  Tests/Realm.Tests/Database/TestObjects.cs
Labels: T-Bug

#1927 Fix the FodyHelpers dependency
  CHANGELOG.md
  Realm.sln
  Realm/Realm.Fody/Realm.Fody.csproj
  Realm/Realm/Realm.csproj
  Tests/Weaver/Realm.Fody.Tests/Realm.Fody.Tests.csproj
Labels: T-Bug

#1915 Fix xml serialization of RealmObject classes
  CHANGELOG.md
  Realm/Realm/RealmObject.cs
  Tests/Realm.Tests/Database/RealmObjectTests.cs
Labels: Pipeline-Review, T-Bug
