Repository realm/realm-dotnet, pull requests merged in 2023-03, with the labels that each got.

#3256 Extract CPU architecture from Unity
  Realm/Realm.UnityWeaver/UnityWeaver.cs
  Realm/Realm.Weaver/Analytics/Analytics.cs
  Realm/Realm.Weaver/Analytics/AnalyticsUtils.cs
  Realm/Realm.Weaver/Analytics/Metric.cs
Labels: cla: yes, no-changelog

#3260 Add a concurrency setting to pr workflow
  .github/templates/pr.yml
  .github/workflows/pr.yml
  CHANGELOG.md
Labels: cla: yes

#3244 Adds minor fixes of bugs discovered while manually testing
  Realm/Realm.Fody/ModuleWeaver.cs
  Realm/Realm.UnityWeaver/UnityWeaver.cs
  Realm/Realm.Weaver/Analytics/Analytics.cs
  Realm/Realm.Weaver/Analytics/AnalyticsUtils.cs
  Realm/Realm.Weaver/Analytics/Metric.cs
  Realm/Realm.Weaver/RealmWeaver.cs
Labels: cla: yes, no-changelog

#3246 Adds hostOS tests to the weaver
  .github/templates/test-weaver.yml
  .github/workflows/test-weaver.yml
  Tests/Weaver/Realm.Fody.Tests/AnalyticsTests.cs
  Tests/Weaver/Realm.Fody.Tests/Realm.Fody.Tests.csproj
Labels: cla: yes, no-changelog

#3259 Add support for compensating writes
  CHANGELOG.md
  Realm/Realm/Exceptions/CompensatingWriteException.cs
  Realm/Realm/Handles/SessionHandle.cs
  Realm/Realm/Native/MarshaledVector.cs
  Realm/Realm/Native/PrimitiveValue.cs
  Realm/Realm/Native/SyncError.cs
  Tests/Realm.Tests/Sync/FlexibleSyncTests.cs
  wrappers/src/error_handling.cpp
  wrappers/src/marshalling.cpp
  wrappers/src/marshalling.hpp
  wrappers/src/notifications_cs.hpp
  wrappers/src/shared_realm_cs.cpp
  wrappers/src/sync_session_cs.cpp
Labels: cla: yes

#3266 Avalonia example suggestions
  examples/SimpleToDoAvalonia/Models/Item.cs
  examples/SimpleToDoAvalonia/Models/ToDoList.cs
  examples/SimpleToDoAvalonia/SimpleToDo.csproj
  examples/SimpleToDoAvalonia/ViewModels/MainViewModel.cs
  examples/SimpleToDoAvalonia/ViewModels/ToDoListCollectionViewModel.cs
  examples/SimpleToDoAvalonia/ViewModels/ToDoListViewModel.cs
  examples/SimpleToDoAvalonia/Views/ToDoListCollectionView.axaml
  examples/SimpleToDoAvalonia/Views/ToDoListView.axaml
Labels: cla: yes

#3263 Create simple project with Avalonia
  README.md
  examples/SimpleToDoAvalonia/App.axaml
  examples/SimpleToDoAvalonia/App.axaml.cs
  examples/SimpleToDoAvalonia/Assets/avalonia-logo.ico
  examples/SimpleToDoAvalonia/DataConverter.cs
  examples/SimpleToDoAvalonia/FodyWeavers.xml
  examples/SimpleToDoAvalonia/Models/Item.cs
  examples/SimpleToDoAvalonia/Models/ToDoList.cs
  examples/SimpleToDoAvalonia/Program.cs
  examples/SimpleToDoAvalonia/README.md
  examples/SimpleToDoAvalonia/SimpleToDo.csproj
  examples/SimpleToDoAvalonia/SimpleToDo.sln
  examples/SimpleToDoAvalonia/ViewLocator.cs
  examples/SimpleToDoAvalonia/ViewModels/MainViewModel.cs
  examples/SimpleToDoAvalonia/ViewModels/MainWindowViewModel.cs
  examples/SimpleToDoAvalonia/ViewModels/ToDoListCollectionViewModel.cs
  examples/SimpleToDoAvalonia/ViewModels/ToDoListViewModel.cs
  examples/SimpleToDoAvalonia/ViewModels/ViewModelBase.cs
  examples/SimpleToDoAvalonia/Views/MainView.axaml
  examples/SimpleToDoAvalonia/Views/MainView.axaml.cs
  examples/SimpleToDoAvalonia/Views/MainWindow.axaml
  examples/SimpleToDoAvalonia/Views/MainWindow.axaml.cs
  examples/SimpleToDoAvalonia/Views/ToDoListCollectionView.axaml
  examples/SimpleToDoAvalonia/Views/ToDoListCollectionView.axaml.cs
  examples/SimpleToDoAvalonia/Views/ToDoListView.axaml
  examples/SimpleToDoAvalonia/Views/ToDoListView.axaml.cs
  examples/SimpleToDoAvalonia/app.manifest
Labels: cla: yes, no-changelog

#3270 Prepare for 10.21.0
  CHANGELOG.md
  Realm/AssemblyInfo.props
  Realm/Realm.Unity/package.json
Labels: cla: yes

#3243 [v11] 10. Annotate projects for nullability
  Realm/Realm.SourceGenerator/Diagnostics.cs
  Realm/Realm.SourceGenerator/DiagnosticsEmitter.cs
  Realm/Realm.SourceGenerator/InfoClasses.cs
  Realm/Realm.SourceGenerator/IsExternalInit.cs
  Realm/Realm.SourceGenerator/NullableAttributes.cs
  Realm/Realm.SourceGenerator/Parser.cs
  Realm/Realm.SourceGenerator/Realm.SourceGenerator.csproj
  Realm/Realm.SourceGenerator/SyntaxContextReceiver.cs
  Realm/Realm.SourceGenerator/Utils.cs
  Realm/Realm.UnityUtils/FileHelper.cs
  Realm/Realm.UnityUtils/Initializer.cs
  Realm/Realm.UnityUtils/Realm.UnityUtils.csproj
  Tools/SetupUnityPackage/CommandLineOptions/RealmOptions.cs
  Tools/SetupUnityPackage/CommandLineOptions/TestOptions.cs
  Tools/SetupUnityPackage/Helpers.cs
  Tools/SetupUnityPackage/PackageInfo.cs
  Tools/SetupUnityPackage/Program.cs
  Tools/SetupUnityPackage/SetupUnityPackage.csproj
Labels: cla: yes

#3273 Remove PermissionDeniedException
  CHANGELOG.md
  Realm/Realm/Exceptions/Sync/ErrorCode.cs
  Realm/Realm/Exceptions/Sync/PermissionDeniedException.cs
  Realm/Realm/Handles/SessionHandle.cs
Labels: Breaking

#3254 [v11] 12. Raise Replace events for collection notifications
  CHANGELOG.md
  Realm/Realm/DatabaseTypes/RealmCollectionBase.cs
  Tests/Realm.Tests/Database/NotificationTests.cs
Labels: cla: yes

#3278 Remove IncompatibleSyncedFileException
  CHANGELOG.md
  Realm/Realm/Exceptions/Sync/IncompatibleSyncedFileException.cs
  Tests/Tests.Android/MainActivity.cs
  Tests/Tests.Android/Properties/AndroidManifest.xml
  Tests/Tests.Android/Tests.Android.csproj
Labels: cla: yes
