Repository realm/realm-dotnet, pull requests merged in 2023-08, with the labels that each got.

#3405 Add a few tests for uncovered code
  Realm/Realm/Transaction.cs
  Tests/Realm.Tests/Database/AsyncTests.cs
  Tests/Realm.Tests/Database/InstanceTests.cs
  Tests/Realm.Tests/Database/RealmSetTests.cs
  Tests/Realm.Tests/Database/ThreadHandoverTests.cs
  Tests/Realm.Tests/Generated/Realm.SourceGenerator/Realms.SourceGenerator.RealmGenerator/A_generated.cs
  Tests/Realm.Tests/Generated/Realm.SourceGenerator/Realms.SourceGenerator.RealmGenerator/B_generated.cs
Labels: cla: yes, no-changelog

#3401 Update QuickJournal
  examples/QuickJournal/AppShell.xaml
  examples/QuickJournal/AppShell.xaml.cs
  examples/QuickJournal/MauiProgram.cs
  examples/QuickJournal/Models/EntryMetadata.cs
  examples/QuickJournal/Models/JournalEntry.cs
  examples/QuickJournal/Platforms/Android/MainActivity.cs
  examples/QuickJournal/Platforms/Android/MainApplication.cs
  examples/QuickJournal/Platforms/MacCatalyst/AppDelegate.cs
  examples/QuickJournal/Platforms/MacCatalyst/Program.cs
  examples/QuickJournal/Platforms/iOS/AppDelegate.cs
  examples/QuickJournal/Platforms/iOS/Program.cs
  examples/QuickJournal/QuickJournal.csproj
  examples/QuickJournal/README.md
  examples/QuickJournal/Resources/AppIcon/appicon.png
  examples/QuickJournal/Resources/AppIcon/appicon.svg
  examples/QuickJournal/Resources/AppIcon/appiconfg.svg
  examples/QuickJournal/Resources/Fonts/OpenSans-Regular.ttf
  examples/QuickJournal/Resources/Fonts/OpenSans-Semibold.ttf
  examples/QuickJournal/Resources/Images/dotnet_bot.svg
  examples/QuickJournal/Resources/Raw/AboutAssets.txt
  examples/QuickJournal/Resources/Splash/mongodb.png
  examples/QuickJournal/Resources/Splash/splash.svg
  examples/QuickJournal/Resources/Styles/Colors.xaml
  examples/QuickJournal/ViewModels/EntriesViewModel.cs
  examples/QuickJournal/ViewModels/EntryDetailViewModel.cs
  examples/QuickJournal/Views/EntriesPage.xaml
  examples/QuickJournal/Views/EntriesPage.xaml.cs
  examples/QuickJournal/Views/EntryDetailPage.xaml
  examples/QuickJournal/Views/EntryDetailPage.xaml.cs
  examples/QuickJournal/Views/JournalEntriesPage.xaml.cs
  examples/QuickJournal/Views/JournalEntryDetailPage.xaml.cs
  examples/QuickJournal/stylecop.json
  examples/QuickJournal/stylecop.ruleset
Labels: cla: yes, no-changelog

#3403 Add new subscribe API
  .editorconfig
  CHANGELOG.md
  Realm/Realm/Extensions/CollectionExtensions.cs
  Realm/Realm/Handles/SessionHandle.cs
  Realm/Realm/Handles/SubscriptionSetHandle.cs
  Realm/Realm/Sync/FlexibleSync/SubscriptionOptions.cs
  Realm/Realm/Sync/FlexibleSync/SubscriptionSet.cs
  Realm/Realm/Sync/FlexibleSync/WaitForSyncMode.cs
  Realm/Realm/Sync/Session.cs
  Tests/Realm.Tests/Generated/Realm.SourceGenerator/Realms.SourceGenerator.RealmGenerator/ObjectWithPartitionValue_generated.cs
  Tests/Realm.Tests/Generated/Realm.SourceGenerator/Realms.SourceGenerator.RealmGenerator/SyncObjectWithRequiredStringList_generated.cs
  Tests/Realm.Tests/Sync/FlexibleSyncTests.cs
  Tests/Realm.Tests/Sync/SessionTests.cs
Labels: cla: yes

#3407 Update charts template
  .github/actions/benchmark-uploader/charts-template.json
Labels: cla: yes

#3409 Pass public_name down to Core
  CHANGELOG.md
  Realm/Realm/Native/Schema.cs
  Realm/Realm/Schema/Property.cs
  Tests/Realm.Tests/Database/AsyncTests.cs
  Tests/Realm.Tests/Database/CollectionTests.cs
  Tests/Realm.Tests/Database/RealmSetTests.cs
  wrappers/src/schema_cs.cpp
  wrappers/src/schema_cs.hpp
Labels: cla: yes

#3406 Fix some resharper warnings
  .github/templates/pr.yml
  .github/workflows/pr.yml
  Realm.sln.DotSettings
  Realm/Realm.PlatformHelpers/Platform.shared.cs
  Realm/Realm.SourceGenerator/ClassCodeBuilder.cs
  Realm/Realm.SourceGenerator/Parser.cs
  Realm/Realm.SourceGenerator/Utils.cs
  Realm/Realm.Weaver/RealmWeaver.cs
  Realm/Realm/Configurations/InMemoryConfiguration.cs
  Realm/Realm/Configurations/RealmConfigurationBase.cs
  Realm/Realm/DataBinding/RealmObjectTypeDelegator.cs
  Realm/Realm/DataBinding/WovenGetterMethodInfo.cs
  Realm/Realm/DataBinding/WovenPropertyInfo.cs
  Realm/Realm/DatabaseTypes/Accessors/ManagedAccessor.cs
  Realm/Realm/DatabaseTypes/Geospatial/GeoPolygon.cs
  Realm/Realm/DatabaseTypes/RealmCollectionBase.cs
  Realm/Realm/DatabaseTypes/RealmDictionary.cs
  Realm/Realm/DatabaseTypes/RealmValue.cs
  Realm/Realm/Dynamic/MetaRealmObject.cs
  Realm/Realm/Exceptions/Sync/ClientResetException.cs
  Realm/Realm/Extensions/StringExtensions.cs
  Realm/Realm/Extensions/TestingExtensions.cs
  Realm/Realm/Handles/AppHandle.cs
  Realm/Realm/Handles/ResultsHandle.cs
  Realm/Realm/Handles/SharedRealmHandle.cs
  Realm/Realm/Handles/UnownedRealmHandle.cs
  Realm/Realm/Helpers/SerializationHelper.cs
  Realm/Realm/Helpers/TaskCompletionSource.cs
  Realm/Realm/InteropConfig.cs
  Realm/Realm/Linq/QueryMethods.cs
  Realm/Realm/Linq/RealmResultsVisitor.cs
  Realm/Realm/Linq/TypeSystem.cs
  Realm/Realm/Logging/Logger.cs
  Realm/Realm/Native/Configuration.cs
  Realm/Realm/Native/HttpClientTransport.cs
  Realm/Realm/Native/MarshaledVector.cs
  Realm/Realm/Native/NativeCommon.cs
  Realm/Realm/Native/PrimitiveValue.cs
  Realm/Realm/Native/Queries/NativeGeoPolygon.cs
  Realm/Realm/Realm.cs
  Realm/Realm/Schema/ObjectSchema.cs
  Realm/Realm/Schema/RealmSchema.cs
  Realm/Realm/Sync/App.cs
  Realm/Realm/Sync/ErrorHandling/DiscardUnsyncedChangesHandler.cs
  Realm/Realm/Sync/ErrorHandling/ManualRecoveryHandler.cs
  Realm/Realm/Sync/ErrorHandling/RecoverOrDiscardUnsyncedChangesHandler.cs
  Realm/Realm/Sync/ErrorHandling/RecoverUnsyncedChangesHandler.cs
  Realm/Realm/Sync/FlexibleSync/Subscription.cs
  Realm/Realm/Sync/FlexibleSync/SubscriptionSet.cs
  Realm/Realm/Sync/MongoClient.cs
  Realm/Realm/Sync/ProgressNotifications/ProgressNotificationToken.cs
  Realm/Realm/Sync/User.cs
  Realm/Realm/Thread Handover/ThreadSafeReference.cs
  Tests/Tests.Maui/Platforms/MacCatalyst/Program.cs
  Tools/DeployApps/BaasClient.cs
  wrappers/src/results_cs.cpp
Labels: cla: yes, no-changelog

#3415 Doc corrections for ClientReset
  Realm/Realm/Configurations/SyncConfigurationBase.cs
  Realm/Realm/Sync/ErrorHandling/ClientResetHandlerBase.cs
Labels: cla: yes, no-changelog

#3416 Avoiding GC of session when there are subscribers
  CHANGELOG.md
  Realm/Realm/Realm.cs
  Realm/Realm/Sync/Session.cs
  Tests/Realm.Tests/Database/RelationshipTests.cs
  Tests/Realm.Tests/Sync/SessionTests.cs
  Tests/Realm.Tests/TestHelpers.cs
Labels: cla: yes

#3412 Platform Networking
  .github/templates/test-code-coverage.yml
  .github/templates/test-net-core.yml
  .github/workflows/test-code-coverage.yml
  .github/workflows/test-net-core.yml
  CHANGELOG.md
  Realm/Realm/Native/AppConfiguration.cs
  Realm/Realm/Native/PrimitiveValue.cs
  Realm/Realm/Native/SyncSocketProvider.EventLoop.cs
  Realm/Realm/Native/SyncSocketProvider.Native.cs
  Realm/Realm/Native/SyncSocketProvider.WebSocket.cs
  Realm/Realm/Native/SyncSocketProvider.cs
  Realm/Realm/Realm.csproj
  Realm/Realm/Sync/App.cs
  Realm/Realm/Sync/AppConfiguration.cs
  Tools/SetupUnityPackage/CommandLineOptions/RealmOptions.cs
  wrappers/CMakeLists.txt
  wrappers/build-apple-platform.ps1
  wrappers/src/CMakeLists.txt
  wrappers/src/app_cs.cpp
  wrappers/src/query_cs.cpp
  wrappers/src/websocket_cs.cpp
  wrappers/src/websocket_cs.hpp
Labels: cla: yes

#3424 Prepare for 11.4.0
  CHANGELOG.md
  Realm/AssemblyInfo.props
  Realm/Realm.Unity/package.json
Labels: cla: yes

#3422 Fix incorrect assertion and cleanup CollectionTests.cs
  Realm.sln.DotSettings
  Tests/Realm.Tests/Database/CollectionTests.cs
Labels: cla: yes, no-changelog

#3420 Fix some API docs for notifications
  Realm/Realm/Linq/IRealmCollection.cs
Labels: no-changelog

#3432 Fix MissingMemberException calls
  CHANGELOG.md
  Realm/Realm/Dynamic/DynamicObjectApi.cs
Labels: cla: yes
