Repository realm/realm-dotnet, pull requests merged in 2023-01, with the labels that each got.

#3133 Update wrappers README
  wrappers/README.md
Labels: cla: yes, no-changelog

#3142 Update bug.yml
  .github/ISSUE_TEMPLATE/bug.yml
Labels: cla: yes, no-changelog

#3145 Fix Realm not getting reinitialized when domain reload is disabled
  CHANGELOG.md
  Realm/Realm.UnityUtils/Initializer.cs
  Realm/Realm/Native/NativeCommon.cs
Labels: cla: yes

#3152 Add no-response workflow to close stale issues
  .github/workflows/no-response.yml
Labels: cla: yes

#3150 Bring back IList conformance to RealmCollectionBase
  CHANGELOG.md
  Realm/Realm/DatabaseTypes/RealmCollectionBase.cs
  Realm/Realm/DatabaseTypes/RealmList.cs
Labels: cla: yes

#3154 Fix string.Contains with .NET 2.1 or higher
  CHANGELOG.md
  Realm/Realm/Linq/RealmResultsVisitor.cs
  Tests/Realm.Tests/Database/RealmResults/SimpleLINQtests.cs
Labels: cla: yes

#3156 Deprecate legacy error codes
  .github/templates/test-ios.yml
  .github/workflows/test-ios.yml
  CHANGELOG.md
  Realm/Realm/DatabaseTypes/RealmDictionary.cs
  Realm/Realm/DatabaseTypes/RealmSet.cs
  Realm/Realm/Exceptions/Sync/ErrorCode.cs
Labels: cla: yes

#3158 Prepare for 10.19.0
  CHANGELOG.md
  Realm/AssemblyInfo.props
  Realm/Realm.Unity/package.json
Labels: cla: yes

#3160 🔄 Synced file(s) with realm/ci-actions
  .github/ISSUE_TEMPLATE/feature.yml
  .github/advanced-issue-labeler.yml
  .github/auto_assign.yml
  .github/workflows/Issue-Needs-Attention.yml
  .github/workflows/auto-assign.yml
  .github/workflows/check-changelog.yml
  .github/workflows/issue-labeler.yml
  .github/workflows/no-response.yml
  LICENSE
Labels: cla: yes, no-changelog

#3165 Build Xamarin.Android tests in all ABIs
  .github/templates/test-android.yml
  .github/workflows/test-android.yml
Labels: cla: yes

#3163 Add more detailed unsupported type error
  CHANGELOG.md
  Realm/Realm.SourceGenerator/Diagnostics.cs
  Realm/Realm.Weaver/RealmWeaver.cs
  Tests/SourceGenerators/SourceGeneratorAssemblyToProcess/Generated/Realm.SourceGenerator/Realms.SourceGenerator.RealmGenerator/UnsupportedIndexableTypes.diagnostics.cs
  Tests/SourceGenerators/SourceGeneratorAssemblyToProcess/Generated/Realm.SourceGenerator/Realms.SourceGenerator.RealmGenerator/UnsupportedPrimaryKeyTypes.diagnostics.cs
  Tests/SourceGenerators/SourceGeneratorAssemblyToProcess/Generated/Realm.SourceGenerator/Realms.SourceGenerator.RealmGenerator/UnsupportedRequiredTypes.diagnostics.cs
  Tests/Weaver/Realm.Fody.Tests/WeaverTests.cs
Labels: cla: yes

#3164 Keep track of the active transaction and close it on realm close
  CHANGELOG.md
  Realm/Realm/Realm.cs
  Tests/Realm.Tests/Database/AsyncTests.cs
  Tests/Realm.Tests/Database/InstanceTests.cs
Labels: cla: yes

#3175 Don't use reflection in DynamicRealmObjectHelper.TryGetPrimaryKeyValue
  CHANGELOG.md
  Realm/Realm/Dynamic/DynamicRealmObjectHelper.cs
  Tests/Realm.Tests/Database/DynamicAccessTests.cs
  Tests/Realm.Tests/Database/TestObjects.cs
  Tests/Realm.Tests/Generated/Realm.SourceGenerator/Realms.SourceGenerator.RealmGenerator/PrivatePrimaryKeyObject_generated.cs
Labels: cla: yes

#3176 Deprecate push client
  CHANGELOG.md
  Realm/Realm/Sync/User.cs
  Tests/Realm.Tests/Sync/UserManagementTests.cs
Labels: cla: yes

#3177 Fix uwp workflow when running in debug
  CHANGELOG.md
  Tests/Tests.UWP/RunTests.ps1
Labels: cla: yes

#3096 Fix failing sync tests
  .github/templates/pr.yml
  .github/templates/test-code-coverage.yml
  .github/templates/test-ios.yml
  .github/workflows/deploy-baas.yml
  .github/workflows/test-code-coverage.yml
  .github/workflows/test-ios.yml
  Realm/Realm/Extensions/TaskExtensions.cs
  Realm/Realm/Handles/SubscriptionSetHandle.cs
  Realm/Realm/Logging/Logger.cs
  Realm/Realm/Realm.cs
  Tests/Realm.Tests/Database/InstanceTests.cs
  Tests/Realm.Tests/Database/NotificationTests.cs
  Tests/Realm.Tests/Generated/Realm.SourceGenerator/Realms.SourceGenerator.RealmGenerator/ObjectWithPartitionValue_generated.cs
  Tests/Realm.Tests/Generated/Realm.SourceGenerator/Realms.SourceGenerator.RealmGenerator/SyncObjectWithRequiredStringList_generated.cs
  Tests/Realm.Tests/Program.cs
  Tests/Realm.Tests/RealmTest.cs
  Tests/Realm.Tests/Sync/AsymmetricObjectTests.cs
  Tests/Realm.Tests/Sync/DataTypeSynchronizationTests.cs
  Tests/Realm.Tests/Sync/FlexibleSyncTests.cs
  Tests/Realm.Tests/Sync/PartitionKeyTests.cs
  Tests/Realm.Tests/Sync/SessionTests.cs
  Tests/Realm.Tests/Sync/SyncConfigurationTests.cs
  Tests/Realm.Tests/Sync/SyncTestBase.cs
  Tests/Realm.Tests/Sync/SyncTestHelpers.cs
  Tests/Realm.Tests/Sync/SynchronizedInstanceTests.cs
  Tests/Realm.Tests/TestHelpers.cs
  Tests/Tests.XamarinMac/Tests.XamarinMac.csproj
  Tests/Tests.XamarinMac/ViewController.cs
  Tools/DeployApps/BaasClient.cs
  wrappers/src/shared_realm_cs.cpp
  wrappers/src/subscription_set_cs.cpp
Labels: cla: yes, no-changelog

#2991 Move realm files created by tests to current directory on CI
  Tests/Benchmarks/PerformanceTests/BenchmarkBase.cs
  Tests/Realm.Tests/RealmTest.cs
Labels: cla: yes, no-changelog

#3193 Bump docker layer caching action to use node16
  .github/templates/common.lib.yml
  .github/workflows/wrappers.yml
Labels: no-changelog

#3200 Workaround Mono yield bug
  CHANGELOG.md
  Realm/Realm.UnityWeaver/Realm.UnityWeaver.csproj
  Realm/Realm.Weaver/RealmWeaver.Schema.cs
Labels: cla: yes

#3206 🔄 Synced file(s) with realm/ci-actions
  .github/advanced-issue-labeler.yml
  .github/workflows/issue-labeler.yml
Labels: cla: yes, no-changelog
