Repository realm/realm-dotnet, pull requests merged in 2023-05, with the labels that each got.

#3304 Guard guid table creation in a write transaction
  CHANGELOG.md
  Tests/Realm.Tests/Database/InstanceTests.cs
  wrappers/src/guid_representation_migration.cpp
Labels: cla: yes

#3307 Hack around Unity editor API change
  CHANGELOG.md
  Directory.build.props
  Realm/Realm.UnityUtils/Realm.UnityUtils.csproj
  Realm/Realm.UnityWeaver/Realm.UnityWeaver.csproj
  Realm/Realm.UnityWeaver/UnityWeaver.cs
Labels: cla: yes

#3310 Allow publishing unity package on prerelease workflow
  .github/templates/common.lib.yml
  .github/templates/publish-prerelease.yml
  .github/templates/publish-release.yml
  .github/workflows/publish-prerelease.yml
  .github/workflows/publish-release.yml
Labels: cla: yes, no-changelog

#3305 Change testing targets to net7.0
  .github/templates/build-packages.yml
  .github/templates/codeql.yml
  .github/templates/main.yml
  .github/templates/pr.yml
  .github/templates/test-android.yml
  .github/templates/test-code-coverage.yml
  .github/templates/test-ios.yml
  .github/templates/test-macos.yml
  .github/templates/test-net-core.yml
  .github/templates/test-source-generation.yml
  .github/templates/test-tvos.yml
  .github/templates/test-woven-classes.yml
  .github/workflows/build-packages.yml
  .github/workflows/codeql.yml
  .github/workflows/main.yml
  .github/workflows/pr.yml
  .github/workflows/test-android.yml
  .github/workflows/test-code-coverage.yml
  .github/workflows/test-ios.yml
  .github/workflows/test-macos.yml
  .github/workflows/test-net-core.yml
  .github/workflows/test-source-generation.yml
  .github/workflows/test-woven-classes.yml
  Tests/Realm.Tests/Realm.Tests.csproj
Labels: cla: yes, no-changelog

#3315 Prepare for 11.0.0
  .github/templates/build-packages.yml
  .github/workflows/build-packages.yml
  CHANGELOG.md
  Realm/AssemblyInfo.props
  Realm/Realm.Unity/package.json
Labels: cla: yes

#3317 Fix a couple of warnings
  Realm/Realm/Linq/QueryMethods.cs
  Tests/Realm.Tests/Database/RealmSetTests.cs
  Tests/Realm.Tests/Database/TestObjects.cs
Labels: no-changelog

#3318 Update ci-actions to latest commit
  .github/templates/common.lib.yml
  .github/templates/test.lib.yml
  .github/workflows/cleanup-baas.yml
  .github/workflows/deploy-baas.yml
  .github/workflows/prepare-release.yml
  .github/workflows/publish-release.yml
  .github/workflows/test-android.yml
  .github/workflows/test-code-coverage.yml
  .github/workflows/test-ios.yml
  .github/workflows/test-macos.yml
  .github/workflows/test-net-core.yml
  .github/workflows/test-net-framework.yml
  .github/workflows/test-tvos.yml
  .github/workflows/test-uwp-managed.yml
  .github/workflows/wipe-clusters.yml
  wrappers/README.md
Labels: cla: yes, no-changelog

#3319 Move the SG and weaver binaries to the Realm package
  .github/templates/common.lib.yml
  .github/templates/main.yml
  .github/templates/publish-release.yml
  .github/templates/test-ios.yml
  .github/templates/test.lib.yml
  .github/workflows/build-packages.yml
  .github/workflows/build-unity.yml
  .github/workflows/codeql.yml
  .github/workflows/main.yml
  .github/workflows/publish-prerelease.yml
  .github/workflows/publish-release.yml
  .github/workflows/test-android.yml
  .github/workflows/test-ios.yml
  .github/workflows/test-macos.yml
  .github/workflows/test-net-core.yml
  .github/workflows/test-net-framework.yml
  .github/workflows/test-tvos.yml
  .github/workflows/test-uwp-managed.yml
  .github/workflows/test-woven-classes.yml
  CHANGELOG.md
  Realm/Realm.Fody/Realm.Fody.csproj
  Realm/Realm/Realm.csproj
  Realm/Realm/wrappers-props/Realm.props
  Realm/Realm/wrappers-props/monoandroid/wrappers.props
  Realm/Realm/wrappers-props/net46/wrappers.props
  Realm/Realm/wrappers-props/xamarinios/wrappers.props
  Realm/Realm/wrappers-props/xamarinmac/wrappers.props
  Realm/Realm/wrappers-props/xamarintvos/wrappers.props
  Tests/Benchmarks/Benchmarks/Benchmarks.csproj
  Tests/Benchmarks/PerformanceTests/PerformanceTests.csproj
  Tests/Realm.Tests/Realm.Tests.csproj
  Tests/Tests.XUnit/Tests.XUnit.csproj
  Tools/SetupUnityPackage/CommandLineOptions/RealmOptions.cs
  Tools/SetupUnityPackage/CommandLineOptions/TestOptions.cs
Labels: cla: yes
