Repository realm/realm-dotnet, pull requests merged in 2023-07, with the labels that each got.

#3365 Reduce number of reg invocations on Unity
  CHANGELOG.md
  Realm/Realm.Weaver/Analytics/Analytics.cs
  Realm/Realm.Weaver/Analytics/AnalyticsUtils.cs
  Realm/Realm.Weaver/RealmWeaver.cs
Labels: cla: yes

#3369 Relax IndexOf conditions to handle null and unmanaged objects
  CHANGELOG.md
  Realm/Realm/DatabaseTypes/RealmList.cs
  Realm/Realm/DatabaseTypes/RealmSet.cs
  Realm/Realm/Handles/SetHandle.cs
  Realm/Realm/Linq/RealmResults.cs
  Tests/Realm.Tests/Database/RealmResults/SimpleLINQtests.cs
  Tests/Realm.Tests/Database/RealmSetTests.cs
  wrappers/src/results_cs.cpp
  wrappers/src/set_cs.cpp
Labels: cla: yes

#3373 Fix NRE on Unity in batch mode
  CHANGELOG.md
  Realm/Realm.UnityWeaver/UnityWeaver.cs
Labels: cla: yes

#3374 Prepare for 11.2.0
  CHANGELOG.md
  Realm/AssemblyInfo.props
  Realm/Realm.Unity/package.json
Labels: cla: yes

#3378 Minor cleanup and add a few tests
  .github/templates/test-code-coverage.yml
  .github/workflows/test-code-coverage.yml
  Realm/Realm/Helpers/LinqHelper.cs
  Realm/Realm/Helpers/Observer.cs
  Tests/Realm.Tests/Database/InMemoryTests.cs
Labels: cla: yes, no-changelog

#3387 Deprecate LocalAppName and LocalAppVersion
  CHANGELOG.md
  Realm/Realm/Native/AppConfiguration.cs
  Realm/Realm/Sync/App.cs
  Realm/Realm/Sync/AppConfiguration.cs
  Tests/Realm.Tests/Sync/AppTests.cs
  wrappers/src/app_cs.cpp
Labels: cla: yes

#3385 Expose base file path and base uri on App
  CHANGELOG.md
  Realm/Realm/Configurations/PartitionSyncConfiguration.cs
  Realm/Realm/Configurations/SyncConfigurationBase.cs
  Realm/Realm/DatabaseTypes/RealmValue.cs
  Realm/Realm/Handles/AppHandle.cs
  Realm/Realm/Handles/SessionHandle.cs
  Realm/Realm/Handles/SyncUserHandle.cs
  Realm/Realm/Native/AppConfiguration.cs
  Realm/Realm/Native/PrimitiveValue.cs
  Realm/Realm/Native/SynchronizationContextScheduler.cs
  Realm/Realm/Realm.cs
  Realm/Realm/Schema/RealmSchema.cs
  Realm/Realm/Sync/App.cs
  Realm/Realm/Sync/AppConfiguration.cs
  Realm/Realm/Sync/FlexibleSync/SubscriptionSet.cs
  Realm/Realm/Sync/User.cs
  Realm/Realm/Thread Handover/ThreadSafeReference.cs
  Realm/Realm/Transaction.cs
  Tests/Realm.Tests/Sync/AppTests.cs
  Tests/Realm.Tests/Sync/SessionTests.cs
  Tests/Realm.Tests/Sync/SyncTestBase.cs
  wrappers/src/app_cs.cpp
Labels: cla: yes

#3379 Fix NRE in IsInRealmNamespace
  CHANGELOG.md
  Realm/Realm.Weaver/Analytics/Analytics.cs
Labels: cla: yes

#3388 Add more extensive coverage for Task.Timeout
  .github/templates/common.lib.yml
  .github/templates/test-code-coverage.yml
  .github/workflows/test-code-coverage.yml
  Tests/Realm.Tests/Database/APITests.cs
Labels: cla: yes, no-changelog

#3389 Add a test for verifying sync log level changes
  Tests/Realm.Tests/Sync/SynchronizedInstanceTests.cs
Labels: no-changelog

#3393 Update MongoDB.Bson to 2.19.1
  Realm/Realm/Helpers/SerializationHelper.cs
  Realm/Realm/Realm.csproj
  Tests/Realm.Tests/Generated/Realm.SourceGenerator/Realms.SourceGenerator.RealmGenerator/Company_generated.cs
  Tests/Realm.Tests/Generated/Realm.SourceGenerator/Realms.SourceGenerator.RealmGenerator/CoordinatesEmbeddedObject_generated.cs
  Tests/Realm.Tests/Generated/Realm.SourceGenerator/Realms.SourceGenerator.RealmGenerator/CustomGeoPoint_generated.cs
  Tests/Realm.Tests/Generated/Realm.SourceGenerator/Realms.SourceGenerator.RealmGenerator/ObjectWithInvalidGeoPoints_generated.cs
  Tests/Realm.Tests/Generated/Realm.SourceGenerator/Realms.SourceGenerator.RealmGenerator/TopLevelGeoPoint_generated.cs
  Tests/Realm.Tests/Generated/Realm.SourceGenerator/Realms.SourceGenerator.RealmGenerator/TypeEmbeddedObject_generated.cs
  Tools/DeployApps/BaasClient.cs
  Tools/DeployApps/DeployApps.csproj
Labels: cla: yes

#3398 Prepare for 11.3.0
  CHANGELOG.md
  Realm/AssemblyInfo.props
  Realm/Realm.Unity/package.json
Labels: cla: yes

#3400 Fix a race between canceling async transaction and Realm.Dispose
  CHANGELOG.md
  Realm/Realm/Handles/SharedRealmHandle.cs
  Tests/Realm.Tests/Database/AsyncTests.cs
Labels: cla: yes
