Repository realm/realm-dotnet, pull requests merged in 2023-09, with the labels that each got.

#3435 Don’t use KeyValuePair in marshaling because it’s overloaded on UWP
  CHANGELOG.md
  Realm/Realm/Native/HttpClientTransport.cs
  Realm/Realm/Native/MarshaledPair.cs
  Realm/Realm/Native/SyncError.cs
Labels: cla: yes

#3438 Fix trailing comma when there are no features to analyze
  Realm/Realm.Weaver/Analytics/Analytics.cs
Labels: no-changelog

#3426 Starting one cluster per platform on CI
  .github/templates/build.lib.yml
  .github/templates/main.yml
  .github/templates/pr.yml
  .github/templates/test-android.yml
  .github/templates/test-code-coverage.yml
  .github/templates/test-ios.yml
  .github/templates/test-macos.yml
  .github/templates/test-net-core.yml
  .github/templates/test-net-framework.yml
  .github/templates/test-uwp-managed.yml
  .github/templates/test-woven-classes.yml
  .github/templates/test.lib.yml
  .github/workflows/cleanup-baas.yml
  .github/workflows/deploy-baas.yml
  .github/workflows/main.yml
  .github/workflows/pr.yml
  .github/workflows/test-android.yml
  .github/workflows/test-code-coverage.yml
  .github/workflows/test-ios.yml
  .github/workflows/test-macos.yml
  .github/workflows/test-net-core.yml
  .github/workflows/test-net-framework.yml
  .github/workflows/test-tvos.yml
  .github/workflows/test-uwp-managed.yml
  .github/workflows/test-woven-classes.yml
  Tools/DeployApps/BaasClient.cs
Labels: cla: yes, no-changelog

#3442 Prepare for 11.5.0
  CHANGELOG.md
  Realm/AssemblyInfo.props
  Realm/Realm.Unity/package.json
Labels: cla: yes

#3450 Update README.md
  wrappers/README.md
Labels: cla: yes, no-changelog

#3451 Allow customizing json ignore attribute for serialized classes
  CHANGELOG.md
  Realm/Realm.SourceGenerator/ClassCodeBuilder.cs
  Realm/Realm.SourceGenerator/CodeEmitter.cs
  Realm/Realm.SourceGenerator/Diagnostics.cs
  Realm/Realm.SourceGenerator/DiagnosticsEmitter.cs
  Realm/Realm.SourceGenerator/GeneratorConfig.cs
  Realm/Realm.SourceGenerator/Parser.cs
  Realm/Realm.SourceGenerator/RealmGenerator.cs
  Realm/Realm/DatabaseTypes/RealmCollectionBase.cs
  Realm/Realm/DatabaseTypes/RealmObjectBase.cs
  Tests/SourceGenerators/SourceGeneratorAssemblyToProcess/.globalconfig
Labels: cla: yes

#3433 Add User.Changed event
  CHANGELOG.md
  Realm/Realm/Handles/RealmHandle.cs
  Realm/Realm/Handles/SessionHandle.cs
  Realm/Realm/Handles/SharedRealmHandle.cs
  Realm/Realm/Handles/SyncUserHandle.cs
  Realm/Realm/Native/NativeCommon.cs
  Realm/Realm/Sync/User.cs
  Tests/Realm.Tests/Sync/UserManagementTests.cs
  wrappers/src/sync_user_cs.cpp
Labels: cla: yes

#3454 Fix typo
  Realm/Realm/Sync/AppConfiguration.cs
Labels: cla: yes
