Repository realm/realm-dotnet, pull requests merged in 2023-02, with the labels that each got.

#3189 Set core version in analytics
  .github/workflows/prepare-release.yml
  Realm/Realm.Weaver/Analytics/Analytics.cs
Labels: cla: yes, no-changelog

#3204 Find installation method for analytics
  Realm/Realm.Fody/ModuleWeaver.cs
  Realm/Realm.UnityWeaver/UnityWeaver.cs
  Realm/Realm.Weaver/Analytics/Analytics.cs
Labels: cla: yes, no-changelog

#3203 Adds stable Id for metrics
  Realm/Realm.Weaver/Analytics/Analytics.cs
  Realm/Realm.Weaver/Analytics/AnalyticsUtils.cs
Labels: cla: yes

#3211 Don't wait for analytics submission
  Realm/Realm.UnityWeaver/Realm.UnityWeaver.csproj
  Realm/Realm.Weaver/Analytics/Analytics.cs
  Realm/Realm.Weaver/RealmWeaver.cs
  Tests/Weaver/Realm.Fody.Tests/AnalyticsTests.cs
Labels: cla: yes, no-changelog

#3218 Allow overriding the version when preparing a release
  .github/workflows/prepare-release.yml
Labels: cla: yes

#3221 Fix copying of wrappers when running tests
  Tests/Realm.Tests/ConfigHelpers.cs
  Tests/Realm.Tests/GlobalSuppressions.cs
  Tests/Realm.Tests/Realm.Tests.csproj
  Tests/Realm.Tests/Sync/SyncTestHelpers.cs
Labels: cla: yes, no-changelog

#3229 Remove survey ad
  README.md
Labels: cla: yes

#3226 Use BsonSerializer.RegisterProvider
  CHANGELOG.md
  Realm/Realm/Helpers/SerializationHelper.cs
  Realm/Realm/Native/NativeCommon.cs
Labels: cla: yes

#3224 Expose options to control sync timeouts
  CHANGELOG.md
  Realm/Realm/Configurations/SyncConfigurationBase.cs
  Realm/Realm/Native/AppConfiguration.cs
  Realm/Realm/Native/SyncConfiguration.cs
  Realm/Realm/Sync/App.cs
  Realm/Realm/Sync/AppConfiguration.cs
  Realm/Realm/Sync/SyncTimeoutOptions.cs
  Tests/Realm.Tests/Sync/SynchronizedInstanceTests.cs
  Tests/Realm.Tests/TestHelpers.cs
  wrappers/src/app_cs.cpp
  wrappers/src/shared_realm_cs.cpp
  wrappers/src/shared_realm_cs.hpp
Labels: cla: yes

#3228 Fix unity hanging while in its sort-of-headless mode
  Realm/Realm.UnityWeaver/UnityWeaver.cs
Labels: cla: yes, no-changelog

#3239 Fix UWP not building on CI
  Realm/Realm.Weaver/Analytics/Analytics.cs
  Realm/Realm.Weaver/Analytics/AnalyticsUtils.cs
  Tests/Weaver/AnalyticsAssembly/Generated/Realm.SourceGenerator/Realms.SourceGenerator.RealmGenerator/AsymmetricTestClass_generated.cs
  Tests/Weaver/AnalyticsAssembly/Generated/Realm.SourceGenerator/Realms.SourceGenerator.RealmGenerator/EmbeddedTestClass_generated.cs
  Tests/Weaver/AnalyticsAssembly/Generated/Realm.SourceGenerator/Realms.SourceGenerator.RealmGenerator/JustForObjectReference_generated.cs
  Tests/Weaver/AnalyticsAssembly/Generated/Realm.SourceGenerator/Realms.SourceGenerator.RealmGenerator/RootRealmClass_generated.cs
Labels: cla: yes, no-changelog

#3232 [v11] 1. Remove error argument from notification callbacks
  CHANGELOG.md
  Realm/Realm/DatabaseTypes/RealmCollectionBase.cs
  Realm/Realm/DatabaseTypes/RealmDictionary.cs
  Realm/Realm/Linq/IRealmCollection.cs
  Tests/Realm.Tests/Database/CollectionTests.cs
  Tests/Realm.Tests/Database/InMemoryTests.cs
  Tests/Realm.Tests/Database/InstanceTests.cs
  Tests/Realm.Tests/Database/ListOfPrimitivesTests.cs
  Tests/Realm.Tests/Database/NotificationTests.cs
  Tests/Realm.Tests/Database/RealmDictionaryTests.cs
  Tests/Realm.Tests/Database/RealmSetTests.cs
  Tests/Realm.Tests/Sync/SessionTests.cs
Labels: Breaking

#3234 [v11] 3. Remove obsolete WriteAsync overloads
  CHANGELOG.md
  Realm/Realm/Realm.cs
  Tests/Realm.Tests/Database/AsyncTests.cs
  Tests/Realm.Tests/Database/InstanceTests.cs
  Tests/Realm.Tests/Database/PropertyChangedTests.cs
  Tests/Realm.Tests/Database/WriteOverloads.cs
Labels: Breaking, cla: yes

#3236 [v11] 4. Remove InMemoryConfiguration.EncryptionKey
  CHANGELOG.md
  Realm/Realm/Configurations/InMemoryConfiguration.cs
  Realm/Realm/Configurations/RealmConfiguration.cs
  Realm/Realm/Configurations/RealmConfigurationBase.cs
  Realm/Realm/Configurations/SyncConfigurationBase.cs
  Tests/Realm.Tests/Database/InMemoryTests.cs
Labels: Breaking, cla: yes

#3237 [v11] 5. Remove a few obsolete Sync API
  CHANGELOG.md
  Realm/Realm/Configurations/SyncConfiguration.cs
  Realm/Realm/Extensions/RealmSyncExtensions.cs
  Realm/Realm/Extensions/TestingExtensions.cs
  Realm/Realm/Handles/SessionHandle.cs
  Realm/Realm/Sync/ErrorHandling/DiscardUnsyncedChangesHandler.cs
  Tests/Realm.Tests/Database/EmbeddedObjectsTests.cs
  Tests/Realm.Tests/Sync/SessionTests.cs
  Tests/Realm.Tests/Sync/SyncConfigurationTests.cs
Labels: Breaking, cla: yes

#3238 [v11] 6. Remove AppConfiguration.CustomLogger
  CHANGELOG.md
  Realm/Realm/Logging/Logger.cs
  Realm/Realm/Sync/App.cs
  Realm/Realm/Sync/AppConfiguration.cs
  Tests/Realm.Tests/Sync/AppTests.cs
Labels: Breaking, cla: yes

#3240 [v11] 7. Remove obsolete schema API
  CHANGELOG.md
  Realm/Realm/Attributes/ExplicitAttribute.cs
  Realm/Realm/Configurations/RealmConfigurationBase.cs
  Realm/Realm/Schema/ObjectSchema.cs
  Realm/Realm/Schema/RealmSchema.cs
  Tests/Realm.Tests/Database/InstanceTests.cs
  Tests/Realm.Tests/Database/ObjectSchemaTests.cs
Labels: Breaking, cla: yes

#3241 [v11] 8. Remove deprecated User.PushClient
  CHANGELOG.md
  Realm/Realm/Handles/SyncUserHandle.cs
  Realm/Realm/Sync/User.cs
  Tests/Realm.Tests/Sync/UserManagementTests.cs
  Tools/DeployApps/BaasClient.cs
  wrappers/src/sync_user_cs.cpp
Labels: Breaking, cla: yes

#3242 [v11] 9. Remove Session.Error
  CHANGELOG.md
  Realm/Realm/Extensions/TestingExtensions.cs
  Realm/Realm/GlobalSuppressions.cs
  Realm/Realm/Handles/SessionHandle.cs
  Realm/Realm/Sync/ErrorHandling/ManualRecoveryHandler.cs
  Realm/Realm/Sync/Session.cs
  Tests/Realm.Tests/Sync/DataTypeSynchronizationTests.cs
  Tests/Realm.Tests/Sync/SessionTests.cs
  Tests/Realm.Tests/Sync/SyncTestHelpers.cs
Labels: Breaking, cla: yes
