Repository realm/realm-dotnet, pull requests merged in 2024-07, with the labels that each got.

#3637 Reenable CollectionMerge test
  Tests/Realm.Tests/Sync/DataTypeSynchronizationTests.cs
Labels: no-changelog, no-jira-ticket

#3645 Test collection listener for updates on embedded object
  Tests/Realm.Tests/Database/NotificationTests.cs
  Tests/Realm.Tests/Database/TestNotificationObject.cs
  Tests/Realm.Tests/Generated/Realm.SourceGenerator/Realms.SourceGenerator.RealmGenerator/TestNotificationObject_generated.cs
Labels: cla: yes, no-changelog, no-jira-ticket

#3651 Add `no-jira-ticket` to release PRs.
  .github/pkl-workflows/publish-release.pkl
  .github/workflows/prepare-release.yml
  .github/workflows/publish-release.yml
Labels: cla: yes

#3652 RNET-1156: Add test for merging new objects
  Tests/Realm.Tests/Database/RealmValueTests.cs
  Tests/Realm.Tests/Database/RealmValueWithCollections.cs
  Tests/Realm.Tests/Database/TestObjects.cs
  Tests/Realm.Tests/Sync/DataTypeSynchronizationTests.cs
Labels: cla: yes
