Repository realm/realm-dotnet, pull requests merged in 2024-04, with the labels that each got.

#3556 [RNET-992] Add sync support for collections in mixed
  Tests/Realm.Tests/Database/RealmValueWithCollections.cs
  Tests/Realm.Tests/Sync/DataTypeSynchronizationTests.cs
  Tools/DeployApps/BaasClient.cs
  wrappers/src/dictionary_cs.cpp
  wrappers/src/list_cs.cpp
  wrappers/src/object_cs.cpp
Labels: cla: yes, no-changelog

#3570 RNET-1132: Add tests for sync schema migration
  Realm.sln.DotSettings
  Tests/Realm.Tests/Database/RealmValueWithCollections.cs
  Tests/Realm.Tests/Generated/Realm.SourceGenerator/Realms.SourceGenerator.RealmGenerator/NullablesV0_generated.cs
  Tests/Realm.Tests/Generated/Realm.SourceGenerator/Realms.SourceGenerator.RealmGenerator/NullablesV1_generated.cs
  Tests/Realm.Tests/Sync/SyncMigrationTests.cs
  Tools/DeployApps/BaasClient.cs
Labels: cla: yes, no-changelog

#3479 RNET-1083: Add support for progress estimate on progress notifications
  CHANGELOG.md
  Realm/Realm/Handles/SessionHandle.cs
  Realm/Realm/Sync/ProgressNotifications/ProgressMode.cs
  Realm/Realm/Sync/ProgressNotifications/ProgressNotificationToken.cs
  Realm/Realm/Sync/ProgressNotifications/SyncProgress.cs
  Realm/Realm/Sync/Session.cs
  Tests/Realm.Tests/Sync/SessionTests.cs
  Tests/Realm.Tests/Sync/SynchronizedInstanceTests.cs
  wrappers/src/async_open_task_cs.cpp
  wrappers/src/sync_session_cs.cpp
  wrappers/src/sync_session_cs.hpp
Labels: cla: yes

#3573 RNET-1133: Fixed equality comparison for collections in mixed
  Realm/Realm/DatabaseTypes/RealmValue.cs
  Tests/Realm.Tests/Database/RealmValueWithCollections.cs
Labels: cla: yes, no-changelog

#3575 Hide collections in mixed from public API
  CHANGELOG.md
  Realm/Realm/DatabaseTypes/RealmValue.cs
  Tests/Realm.Tests/Database/RealmValueWithCollections.cs
  Tests/Realm.Tests/Sync/DataTypeSynchronizationTests.cs
Labels: cla: yes, no-jira-ticket

#3578 Prepare for 12.0.0
  CHANGELOG.md
  Realm/AssemblyInfo.props
  Realm/Realm.Unity/package.json
Labels: cla: yes, no-jira-ticket

#3568 Update to new documentation URL
  Docs/index.md
  NuGet.md
  README.md
  Realm/Realm.SourceGenerator/Realm.SourceGenerator.csproj
  Realm/Realm.Unity/README.md
  Realm/Realm.Unity/package.json
  Realm/Realm.UnityUtils/Realm.UnityUtils.csproj
  Realm/Realm/Configurations/FlexibleSyncConfiguration.cs
  Realm/Realm/Configurations/PartitionSyncConfiguration.cs
  Realm/Realm/Configurations/SyncConfigurationBase.cs
  Realm/Realm/Exceptions/RealmMigrationNeededException.cs
  Realm/Realm/Exceptions/RealmSchemaValidationException.cs
  Realm/Realm/Exceptions/Sync/ErrorCode.cs
  Realm/Realm/Extensions/CollectionExtensions.cs
  Realm/Realm/Helpers/AsyncHelper.cs
  Realm/Realm/Migration.cs
  Realm/Realm/Schema/ObjectSchema.cs
  Realm/Realm/Sync/ApiKey.cs
  Realm/Realm/Sync/Credentials.cs
  Realm/Realm/Sync/ErrorHandling/ClientResetHandlerBase.cs
  Realm/Realm/Sync/ErrorHandling/DiscardUnsyncedChangesHandler.cs
  Realm/Realm/Sync/ErrorHandling/ManualRecoveryHandler.cs
  Realm/Realm/Sync/ErrorHandling/RecoverOrDiscardUnsyncedChangesHandler.cs
  Realm/Realm/Sync/ErrorHandling/RecoverUnsyncedChangesHandler.cs
  Realm/Realm/Sync/User.cs
  SUPPORT.md
Labels: cla: yes, no-changelog, no-jira-ticket

#3587 RNET-1109: Add App.UpdateBaseUri
  CHANGELOG.md
  Realm/Realm/Handles/AppHandle.cs
  Realm/Realm/Helpers/ExperimentalAttribute.cs
  Realm/Realm/Sync/App.cs
  Tests/Realm.Tests/Sync/AppTests.cs
  wrappers/src/app_cs.cpp
Labels: cla: yes
