Repository realm/realm-dotnet, pull requests merged in 2024-05, with the labels that each got.

#3590 Prepare for 12.1.0
  CHANGELOG.md
  Realm/AssemblyInfo.props
  Realm/Realm.Unity/package.json
Labels: cla: yes, no-jira-ticket

#3593 RNET-1130: Fail action if tests aren't passing
  .github/templates/test.lib.yml
  .github/workflows/test-android.yml
  .github/workflows/test-code-coverage.yml
  .github/workflows/test-ios.yml
  .github/workflows/test-macos.yml
  .github/workflows/test-net-core.yml
  .github/workflows/test-net-framework.yml
  .github/workflows/test-source-generation.yml
  .github/workflows/test-tvos.yml
  .github/workflows/test-unity.yml
  .github/workflows/test-uwp-managed.yml
  .github/workflows/test-weaver.yml
  .github/workflows/test-woven-classes.yml
Labels: cla: yes, no-changelog

#3601 RNET-1145, RNET-1143: Fix reading schema from native
  CHANGELOG.md
  Realm/Realm/Handles/SharedRealmHandle.cs
  Realm/Realm/Migration.cs
  Realm/Realm/Native/PrimitiveValue.cs
  Realm/Realm/Realm.cs
  Realm/Realm/Schema/Property.cs
  Tests/Realm.Tests/Database/MigrationTests.cs
  Tests/Realm.Tests/Generated/Realm.SourceGenerator/Realms.SourceGenerator.RealmGenerator/Dotnet_3597_Old_generated.cs
  Tests/Realm.Tests/Generated/Realm.SourceGenerator/Realms.SourceGenerator.RealmGenerator/Dotnet_3597_generated.cs
  wrappers/src/shared_realm_cs.cpp
Labels: cla: yes

#3608 Prepare for 12.2.0
  CHANGELOG.md
  Realm/AssemblyInfo.props
  Realm/Realm.Unity/package.json
  Tests/Realm.Tests/Sync/UserManagementTests.cs
Labels: cla: yes
